# [colors]
# foreground = "#ebdbb2"

# [colors.bright]
# black = "#928374"
# blue = "#83a598"
# cyan = "#8ec07c"
# green = "#b8bb26"
# magenta = "#d3869b"
# red = "#fb4939"
# white = "#ebdbb9"
# yellow = "#fabd2f"
#
# [colors.cursor]
# cursor = "#ebdbb2"
# text = "#282828"
#
# [colors.normal]
# black = "#282828"
# blue = "#458588"
# cyan = "#689d6a"
# green = "#98971a"
# magenta = "#b16286"
# red = "#cc241d"
# white = "#a89984"
# yellow = "#d79921"
#
# [colors.primary]
# background = "#282828"
#
# [colors.selection]
# background = "#3c3836"
# text = "#d5c4a1"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "SemiBold Italic"

[font.normal]
family = "JetBrains Mono"
style = "SemiBold"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
opacity = 0.95

[window.padding]
x = 5
y = 5

# Kanagawa Wave Alacritty Colors

[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

[colors.normal]
black = '#090618'
red = '#c34043'
green = '#76946a'
yellow = '#c0a36e'
blue = '#7e9cd8'
magenta = '#957fb8'
cyan = '#6a9589'
white = '#c8c093'

[colors.bright]
black = '#727169'
red = '#e82424'
green = '#98bb6c'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#dcd7ba'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
